main.py
moview/modules/analyzer/input_info_analyzer.py
moview/modules/question_generator/follow_up_question_generator.py
moview/modules/question_generator/init_question_generator.py

- ChatManager를 받은 상태에서 또 재할당하는 코드가 있어서 제거했습니다.
- API로 호출했을 때, 평가결과 스트링을 받을 수 있도록 return을 추가했습니다.
- 이전 PR에서 받았던 리뷰내용을 반영했습니다. (#6)

Module refactoring

---

moview/controller/__init__.py
moview/controller/evaluation_controller.py
moview/controller/generation_controller.py
moview/utils/data_manager.py

PR #12 에서 받았던 리뷰들에 대한 반영입니다!
1. 유사 함수 통합
2. 타입힌트 오류 수정
3. 예외처리에 대한 범위지정

Flask 코드 리팩토링

---

.github/workflows/cicd.yml
moview/__init__.py
moview/controller/__init__.py
moview/controller/evaluation_controller.py
moview/controller/generation_controller.py

EC2에서 아래의 에러가 발생하여 해결하였습니다.
```
Traceback (most recent call last): 
File "app.py", line 1, in <module>
from moview import app
File "/home/ubuntu/app/moview/__init__.py", line 7, in <module>
from controller import evaluation_controller
ModuleNotFoundError: No module named 'controller'
```
해당 문제는 기존에 PyCharm IDE에서 moview 디렉토리를 **Sources root로 Marking**하여 해결했던 문제를 EC2에서는 그 해결 방법을 활용할 수 없어서 발생한 문제로, **import를 할 때 full path**를 적어줌으로써 해결하였습니다.  
이 외에도,
- 기존에 Github Actions에서 제공하는 환경 변수를 이용하여 이름을 붙임으로써 S3의 배포 파일에 대해서 버전 관리를 하던 것이 불필요하다 판단되어 **moview_core라는 하나의 이름으로 관리**하도록 변경하였고,
- test coverage를 체크하는 step의 이름이 불분명하다는 피드백을 받아들여 **Check Test Coverage Threshold** 라는 이름으로 변경하였습니다.

EC2의 module import error 해결

---

.github/workflows/cicd.yml

헷갈리지 않도록 frontend의 ci/cd와 주석을 통일했고, 이후에 활용할 테스트 커버리지 출력 문구 관련해서 약간의 수정을 했습니다.

frontend ci/cd와 주석 및 코드 통일

---

scripts/after_install/install_aws_cli.sh

!HOTFIX: 권한 부족으로 인한 AWS CLI 설치 오류 해결

---

.github/workflows/cicd.yml

- 모든 branch에 대해서 push가 발생 했을 때마다 테스트를 실행하는 로직 추가
- main에 push를 진행할 때 외에도 직접 deploy 워크플로우를 실행할 수 있도록 로직 변경

refactor: CI/CD 로직 추가

---

README.md
moview/__init__.py
moview/controller/interviewee_answer_controller.py
moview/controller/interviewee_session_controller.py
moview/controller/interviwee_input_controller.py
moview/repository/entity/interviewee_data_main_document.py
moview/repository/entity/interviewee_data_subdocument.py
moview/service/interviewee_answer/interviewee_answer_service.py
moview/service/interviewee_answer/interviewer_action_enum.py
moview/service/interviewee_input/interviewee_input_service.py
tests/service/interviewee_answer/test_interviewee_answer_service.py
tests/service/interviewee_input/test_interviewee_input_service.py

1. session 발급용 컨트롤러 생성 및 테스트 완료
2. input_controller 완성 및 테스트 (포스트맨)
3. answer_controller 완성 및 테스트(포스트맨) <- 전체 시나리오 테스팅은 아직

Feat add controller

---

moview/controller/interviewee_answer_controller.py
moview/controller/interviewee_session_controller.py
moview/controller/interviwee_input_controller.py
moview/repository/entity/interviewee_data_subdocument.py
moview/service/interviewee_answer/interviewee_answer_service.py
moview/service/interviewee_evaluation/interviewee_answer_evaluation_service.py
moview/service/interviewee_input/interviewee_input_service.py
tests/service/interviewee_answer/test_interviewee_answer_service.py
tests/service/interviewee_evaluation/test_interviewee_answer_evaluation_service.py
tests/service/interviewee_input/test_interviewee_input_service.py

[한 일]
1. 각 로직에 로그 작성 후, 몽고 db에 테스트 완료
2.백엔드 전체 컨트롤러 시나리오 통합 테스트
[완료한 테스트 시나리오] 가정 : 초기 질문 2개, 꼬리질문 3개씩임.
```
1. Session: 세션 발급 및 몽고 db 저장 테스트
2. Input: 초기 출제 테스트 및 db 저장 테스트
3. Answer : INAPPROPRIATE_ANSWER + 초기 질문으로 넘어가는 시나리오
4. Answer : DIRECT_REQUEST + 초기 질문으로 넘어가는 시나리오
5. Answer : 질문 2개만 있는 상황에서 INAPPROPRIATE_ANSWER-> DIRECT_REQUEST 시나리오 (END_INTERVIEW 반환하게 수정) ,DIRECT_REQUEST->DIRECT_REQUEST, INAPPROPRIATE_ANSWER->INAPPROPRIATE_ANSWER 시나리오도 다 테스트함.
6. Answer : 초기 질문 정상 답변-> 꼬리 질문에서 INAPPROPRIATE_ANSWER->다음 초기 질문에서 INAPPROPRIATE_ANSWER->END_INTERVIEW
7. Answer : 초기 질문 정상 답변 -> 꼬리 질문 정상 답변 2개 -> 꼬리 질문에서 INAPPROPRIATE_ANSWER -> 다음 초기 질문 INAPPROPRIATE_ANSWER ->END_INTERVIEW
8. Answer : 초기 질문 정상 답변 -> 꼬리 질문에서 INAPPROPRIATE_ANSWER -> 초기 질문 정상 답변-> ->꼬리 질문에서 …
```

Test and fix

---

moview/domain/entity/interview_session_document.py
moview/domain/entity/question_answer/answer.py
moview/domain/entity/question_answer/question.py
moview/modules/question_generator/__init__.py
moview/modules/question_generator/answer_category_classifier.py
moview/modules/question_generator/answer_filter.py
moview/modules/question_generator/answer_sub_category_classifier.py
moview/modules/question_generator/answer_validator.py
moview/modules/question_generator/followup_question_giver.py
moview/repository/interview_repository.py
moview/repository/question_answer/question_answer_repository.py
moview/service/answer_service.py
moview/service/interviewee_answer/interviewee_answer_service.py
tests/common_code_for_test.py
tests/modules/question_generator/test_answer_category_classifier.py
tests/modules/question_generator/test_answer_filter.py
tests/modules/question_generator/test_answer_sub_category_classifier.py
tests/modules/question_generator/test_answer_validator.py
tests/modules/question_generator/test_followup_question_giver.py
tests/repository/test_question_answer_repository.py
tests/service/test_answer_service.py

1. Objectid 넣는 것 수정
2. 로거에 id 등 파라미터 추가
3. 리턴 값 타입 추가
4. 엔티티 내 변수 명 변경 (prev_question_id)
5. AnswerFilter -> AnswerValidator 로 이름 변경
6. 꼬리 질문의 꼬리 질문 테스트하는 코드 추가.

Refactor answer_2

---

moview/controller/dto/feedback_dto.py
moview/repository/question_answer/question_answer_repository.py
moview/service/answer_service.py
moview/service/feedback_service.py
tests/service/test_feedback_service.py

1. 피드백 서비스 추가
2. 피드백 서비스 테스트 코드 작성 및 수행 완료

Feat feedback

---

.github/workflows/dev_pr.yml
.github/workflows/dev_push.yml
.github/workflows/feat_push.yml

dev 브랜치를 위한 CI/CD 파이프라인을 구성했습니다.
dev 배포를 위해서 새롭게 추가한 구성 요소들입니다.
1. dev 배포용 **EC2** 생성
2. dev 배포용 **탄력적 IP** 생성
3. dev 배포용 **S3** 생성
4. dev 배포용 **CodeDeploy 배포 그룹** 생성
5. dev 배포용 **Github Actions workflow** 생성
6. dev 배포용 **Github Repository Secret Key** 추가 (DEV_S3_BUCKET_NAME, DEV_CODE_DEPLOY_GROUP_NAME)
기존 내용을 활용한 것들은 다음과 같습니다.
1. 보안 그룹(moview-core-security)
2. 키 페어(moview-core-ec2)
3. IAM 역할(moview-cicd-ec2-role, moview-cicd-codedeploy-role)
4. CodeDeploy 애플리케이션
5. CodeDeploy 설정 파일(appspec.yml) 및 쉘 스크립트
6. 파라미터 스토어의 환경 변수 (prod)
1) 현재 MongoDB 관련 설정(mongod 서비스 시작, admin id/pw 설정)을 직접 해야 합니다. 도커로 재구성할 때 참고.
2) boto3(Python의 AWS CLI 라이브러리)를 위한 AWS_DEFAULT_REGION 환경 변수 추가 쉘 스크립트가 최근에 추가되었고, 잘 작동 하여 ~/.bashrc 에 환경 변수가 있는 것이 확인 되었음에도 인식을 못하고 빌드 에러가 발생
-> 도커로 재구성할 예정이기 때문에 참고만 할 것

feat: dev 브랜치용 CI/CD 파이프라인 구성

---

moview/controller/answer_controller.py
moview/controller/evaluation_controller.py
moview/controller/feedback_controller.py
moview/controller/input_data_controller.py
moview/modules/answer_evaluator/answer_evaluator.py
moview/service/evaluation_service.py
tests/service/test_evaluation_service.py

현재 코드에 맞도록 주석을 변경하고, 추적에 도움을 주기 위해 좀 더 자세한 값을 로깅하도록 변경했습니다.

request: evaluation 주석 및 로그 변경

---

moview/repository/input_data/input_data_repository.py
moview/repository/interview_repository.py
moview/repository/question_answer/question_answer_repository.py

... 임시 방편으로 mongoclient 수정했습니다.

hot-fix : 배포에서 db 연결이 안되는 오류 수정

---

app.py
moview/repository/input_data/input_data_repository.py
moview/repository/interview_repository.py
moview/repository/question_answer/question_answer_repository.py

Release v1.1

---

moview/modules/input/input_analyzer.py
moview/modules/question_generator/followup_question_giver.py
tests/service/test_input_service.py
tests/service/test_light_mode_service.py

- retry_decorator의 import문 경로 수정
- 테스트 코드에 미반영된 수정 사항 적용
- 확률적으로 성공하는 테스트 코드 수정

!HOTFIX: 잘못된 import 경로 수정 및 테스트 수정

---

app.py
moview/config/jwt/jwt_config.py
scripts/application_start/deploy.sh
scripts/application_stop/stop_application.sh

1. 서브도메인이 달라서 Cross Domain 문제가 발생함.
2. 해결을 위해, JWT 쿠키 전달시 SameSite 옵션을 "None"으로, DomainName을 ".moview.io"로 설정.
1. Gunicorn에 맞춰서 프로세스 실행, 중지 스크립트 수정.

!HOTFIX: Cross Domain Cookie

---

app.py
moview/controller/input_data_controller.py
moview/controller/light_mode_controller.py
moview/service/interview_service.py

dict로 전달되어야 하는 값이 str으로 전달되어서 발생한 문제

fix: input_data_document의 잘못된 타입으로 인한 오류 수정

---

scripts/application_start/deploy.sh

deploy.sh에 배포 직전에 .bashrc를 로딩 하는 로직 추가

feat: 배포 직전에 환경 변수를 로딩하는 로직 추가

---

app.py
moview/controller/health_controller.py

1. 서버 상태를 체크하기 위한 Health Check API 추가.

Feat: health check api

---

Dockerfile

Dockerfile에 localtime을 수정하는 명령어를 추가하여 docker 컨테이너의 timezone을 서울 시간으로 고정했습니다.

!HOTFIX: 도커 컨테이너의 timezone 수정
